project:
  type: book

book:
  title: "ADA compliance notes"
  author: "CSI Math department"
  date: now
  search: true
  repo-url: https://github.com/mth229/CSI-Math-ADA
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - ada-tools.qmd
    - webwork.qmd
    - webassign.qmd
    - achieve.qmd
    - latex.qmd
    - markdown.qmd
    - quarto.qmd
    - ms-word.qmd

format:
  html:
    theme: spacelab
    number-depth: 3
    toc-depth: 3
    link-external-newwindow: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@3.1.0/dist/css/sa11y.min.css"/>
          <script src="https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.1.0/dist/js/lang/en.umd.js,gh/ryersondmp/sa11y@3.1.0/dist/js/sa11y.umd.min.js"></script>
    include-after-body:
      - text: |
          <script>Sa11y.Lang.addI18n(Sa11yLangEn.strings);
          const sa11y = new Sa11y.Sa11y({checkRoot:"body"});
          </script>
execute:
  error: true
  freeze: false # auto
