# Notes on LaTeX

> Because LaTeX was designed as a typesetting program, PDF documents created using LaTeX do not include the document structure and tagging required for accessibility by default. It is possible to create accessible PDF documents using LaTeX but users will need to use additional LaTeX packages and should be aware of accessibility standards. The Accessibilty package in LaTeX can be used to add the structure, tagging, and alt text that PDF's created with LaTeX lack.
>
> From [LaTeX Guides](https://libguides.lib.msu.edu/c.php?g=995742&p=8207771)

The support of tagged PDF within \LaTeX is ongoing. The most up-to-date report is [available here][1].

Here is a sample preamble with additions for accessibility:
```tex
\DocumentMetadata{
    testphase=phase-III, % enables tagging
    pdfstandard=A-2b     % declares that the pdf supports the A-2b standard
                         % note: this is only metadata, it does not enforce
                         % nor test anything
}
\documentclass{article}     % unclear if amsart is supported, needs more testing
\usepackage[utf8]{inputenc} % unrelated to accessibility
\usepackage{hyperref}

\hypersetup{
    pdflang=en-US,
    pdftitle={<title of PDF>},
    pdfauthor={<author>}
}
```

Additional recommendations:

* Use the most up-to-date version of latex/pdflatex available.
* PDFLaTeX or LuaLaTeX support tagging, other engines (e.g. XeTeX) are untested and may not work
* As with HTML, you should write your document using structured tags (`\section`, `\subsection`) so that these can be communicated to e-readers.
* Likewise, pictures should include alt-text, e.g. `\includegraphic[alt={Rubber Duck}]{ducky.jpg}`
* There is also an early prototype for tagging formulas. Use `\DocumentMetadata{testphase={phase-III,math}}` to load.
* See the [LaTeX project's report][1] for full details

::: {.callout-note}
## Note
Documentation for supported key/values for `\DocumentMetadata` [is given here](https://texdoc.org/serve/documentmetadata-support/0).

I (TG) am unable to find more information about what level of the PDF/A standard is supported by LaTeX right now.

The above recipe scores 100% on Blackboard's accessibility checker but more in depth testing is needed (and welcome!).
:::


## Packages

::: {.callout-note}
## These may all be outdated

:::

::: {.callout-note}
## Caution
This package is not meant for direct use for end users.
:::

* [tagpdf](https://ctan.org/pkg/tagpdf?lang=en)


The package offers tools to experiment with tagging and accessibility using pdfLATEX and LuaTEX. It isn’t meant for production but allows the user to try out how difficult it is to tag some structures; to try out how much tagging is really needed; to test what else is needed so that a pdf works e.g. with a screen reader. Its goal is to get a feeling for what has to be done, which kernel changes are needed, how packages should be adapted.

::: {.callout-note}
## Wait!

This package is not actively developed. Please read the [author's README](https://github.com/AndyClifton/accessibility) for more info.
:::

* [accessibility](https://ctan.org/pkg/accessibility?lang=en)

The accessibility package is intended to create tagged, structured PDF documents from LATEX source code. It allows to produce tagged PDF output following Adobe’s PDF-1.5 and 1.6 specifications.

::: {.callout-note}
## Wait!

As of 2020 the author discourages the use of this package.

:::


* [axessiblity](https://ctan.org/pkg/axessibility?lang=en)

PDF documents containing formulas generated by LATEX are usually not accessible by assistive technologies for visually impaired people and people with special educational needs (i.e., by screen readers and braille displays). The axessibility package manages this issue, allowing to create a PDF document where the formulas are read by these assistive technologies, since it automatically generates hidden comments in the PDF document (by means of the /ActualText attribute and/or suitable tags) in correspondence to each formula.

## Further reading

Some links of interest (re: accessible LaTeX):

* [https://www.ams.org/journals/notices/202301/rnoti-p68.pdf](https://www.ams.org/journals/notices/202301/rnoti-p68.pdf)

* [https://libguides.lib.msu.edu/c.php?g=995742&p=8207771](https://libguides.lib.msu.edu/c.php?g=995742&p=8207771)

* [https://tex.stackexchange.com/questions/261537/a-guide-on-how-to-produce-accessible-pdf-files](https://tex.stackexchange.com/questions/261537/a-guide-on-how-to-produce-accessible-pdf-files)

* [PDF-A Compliant LaTeX](https://shen.hong.io/reproducible-pdfa-compliant-latex/)

[1]: https://www.latex-project.org/publications/2023-UFi-FMi-TUG-tb137fischer-tagging23.pdf
